version: "3"
services:
  web:
    image: akyla/testrepo:exercise
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    networks:
      - webnet

  influxdb:
    image: library/influxdb:1.5
    restart: always
    environment:
        - INFLUXDB_DB=exercise
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=adminPass
    ports:
      - "8086:8086"

networks:
  webnet: